package com.vehiclediag.app.data.models

import com.google.gson.annotations.SerializedName

/**
 * Complete vehicle telemetry data from backend.
 */
data class VehicleTelemetry(
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("speed") val speed: Double = 0.0,
    @SerializedName("battery") val battery: BatteryHealth = BatteryHealth(),
    @SerializedName("tires") val tires: TireStatus = TireStatus(),
    @SerializedName("odometer") val odometer: Double = 0.0,
    @SerializedName("engine_status") val engineStatus: String = "unknown"
)

/**
 * Battery state of charge and health.
 */
data class BatteryHealth(
    @SerializedName("soc") val soc: Double = 0.0,
    @SerializedName("voltage") val voltage: Double = 0.0,
    @SerializedName("temperature") val temperature: Double = 0.0,
    @SerializedName("health_status") val healthStatus: String = "Unknown"
)

/**
 * Tire pressure for all four tires.
 */
data class TireStatus(
    @SerializedName("front_left") val frontLeft: Double = 0.0,
    @SerializedName("front_right") val frontRight: Double = 0.0,
    @SerializedName("rear_left") val rearLeft: Double = 0.0,
    @SerializedName("rear_right") val rearRight: Double = 0.0
)

/**
 * Alert generated by the health analytics engine.
 */
data class AlertModel(
    @SerializedName("id") val id: String = "",
    @SerializedName("alert_type") val alertType: String = "",
    @SerializedName("severity") val severity: String = "info",
    @SerializedName("message") val message: String = "",
    @SerializedName("signal") val signal: String = "",
    @SerializedName("value") val value: Double = 0.0,
    @SerializedName("threshold") val threshold: String = "",
    @SerializedName("timestamp") val timestamp: String = "",
    @SerializedName("acknowledged") val acknowledged: Boolean = false
)

/**
 * Simulation status from backend.
 */
data class SimulationStatus(
    @SerializedName("running") val running: Boolean = false,
    @SerializedName("tick_count") val tickCount: Int = 0,
    @SerializedName("start_time") val startTime: String? = null,
    @SerializedName("message") val message: String = ""
)

/**
 * Speed response from /vehicle/speed endpoint.
 */
data class SpeedResponse(
    @SerializedName("speed") val speed: Double = 0.0,
    @SerializedName("unit") val unit: String = "km/h",
    @SerializedName("timestamp") val timestamp: String = ""
)

/**
 * Dynamic signal configuration for OTA.
 */
data class SignalConfigResponse(
    @SerializedName("signals") val signals: List<SignalConfig> = emptyList(),
    @SerializedName("count") val count: Int = 0
)

data class SignalConfig(
    @SerializedName("id") val id: String = "",
    @SerializedName("name") val name: String = "",
    @SerializedName("unit") val unit: String = "",
    @SerializedName("min") val min: Double = 0.0,
    @SerializedName("max") val max: Double = 0.0,
    @SerializedName("normal_range") val normalRange: List<Double> = emptyList(),
    @SerializedName("ui_widget") val uiWidget: String = ""
)
