"""
Pydantic models for Vehicle Health & Diagnostics system.
Defines data structures for telemetry, battery health, tire status, and alerts.
"""

from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import datetime
from enum import Enum


class AlertSeverity(str, Enum):
    """Alert severity levels."""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


class TireStatus(BaseModel):
    """Tire pressure status for all four tires."""
    front_left: float = Field(default=32.0, ge=0, le=50, description="Front left tire pressure in PSI")
    front_right: float = Field(default=32.0, ge=0, le=50, description="Front right tire pressure in PSI")
    rear_left: float = Field(default=32.0, ge=0, le=50, description="Rear left tire pressure in PSI")
    rear_right: float = Field(default=32.0, ge=0, le=50, description="Rear right tire pressure in PSI")


class BatteryHealth(BaseModel):
    """Battery state of charge and health information."""
    soc: float = Field(default=100.0, ge=0, le=100, description="State of Charge in percentage")
    voltage: float = Field(default=400.0, ge=0, description="Battery voltage in volts")
    temperature: float = Field(default=25.0, description="Battery temperature in Celsius")
    health_status: str = Field(default="Good", description="Overall battery health status")


class VehicleTelemetry(BaseModel):
    """Complete vehicle telemetry data."""
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    speed: float = Field(default=0.0, ge=0, le=200, description="Vehicle speed in km/h")
    battery: BatteryHealth = Field(default_factory=BatteryHealth)
    tires: TireStatus = Field(default_factory=TireStatus)
    odometer: float = Field(default=0.0, ge=0, description="Total distance in km")
    engine_status: str = Field(default="running", description="Engine/motor status")


class AlertModel(BaseModel):
    """Alert generated by the health analytics engine."""
    id: str = Field(description="Unique alert identifier")
    alert_type: str = Field(description="Type of alert (e.g., battery_degradation)")
    severity: AlertSeverity = Field(description="Alert severity level")
    message: str = Field(description="Human-readable alert message")
    signal: str = Field(description="Signal that triggered the alert")
    value: float = Field(description="Signal value at time of alert")
    threshold: str = Field(description="Threshold condition that was violated")
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    acknowledged: bool = Field(default=False, description="Whether the alert has been acknowledged")


class SimulationStatus(BaseModel):
    """Status of the vehicle data simulator."""
    running: bool = Field(default=False, description="Whether simulation is active")
    tick_count: int = Field(default=0, description="Number of simulation ticks completed")
    start_time: Optional[str] = Field(default=None, description="Simulation start timestamp")
    message: str = Field(default="Simulator idle", description="Status message")


class SignalConfig(BaseModel):
    """Configuration for a single vehicle signal (loaded from config)."""
    id: str
    name: str
    unit: str
    min: float
    max: float
    normal_range: List[float]
    ui_widget: str
    analytics_rules: List[dict] = []


class BlueprintOutput(BaseModel):
    """Output of the GenAI requirement interpreter."""
    signals: List[str]
    services: List[str]
    ui_components: List[str]
    alerts: List[str]
    raw_requirement: str = ""
